app/authors/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter

from . import views

app_name = 'authors'

router = SimpleRouter()
router.register('api/v2', views.AuthorViewSet, basename='author-api')

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('register/create/', views.register_create, name='register_create'),
    path('login/', views.login_view, name='login'),
    path('login/create/', views.login_create, name='login_create'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path(
        'dashboard/recipe/new/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_new'),
    path(
        'dashboard/recipe/<int:id>/edit/',
        views.DashboardRecipe.as_view(),
        name='dashboard_recipe_edit'
    ),
    path(
        'dashboard/recipe/delete/',
        views.DashboardRecipeDelete.as_view(),
        name='dashboard_recipe_delete'
    ),
    path(
        'profile/<int:id>/',
        views.ProfileView.as_view(),
        name='profile'
    ),
]

urlpatterns += router.urls

app/recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.RecipeListHome.as_view(), name='home'),
    path('recipes/search/', views.RecipeListSearch.as_view(), name='search'),
    path('recipes/tags/<slug:slug>',
         views.RecipeListTag.as_view(), name='tag'),
    path('recipes/category/<int:category_id>/',
         views.RecipeListCategory.as_view(), name='category'),
    # flake8:noqa
    path('recipes/<int:pk>/', views.RecipeDetail.as_view(), name='recipe'),

    path('recipes/api/v1/', views.RecipeListHomeApi.as_view(), name='recipes_api'),
    path('recipes/api/<int:pk>/', views.RecipeDetailApi.as_view(), name='recipe_api'),

    path('theory', views.theory, name='theory'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.recipes.urls')),
    path('authors/', include('app.authors.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/recipes/views/all.py
import os

# from utils.recipes.factory import make_recipe

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


# def home(request):
#     recipes = Recipe.objects.filter(is_published=True).order_by('-id')

#     page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

#     return render(request, 'recipes/pages/home.html', context={
#         'recipes': page_obj,
#         'pagination_range': pagination_range,
#     })


# def category(request, category_id):
#     # recipes = Recipe.objects.filter(
#     #     category__id=category_id, is_published=True).order_by('-id')
#     # if not recipes:
#     #     raise Http404('Not Found')

#     recipes = get_list_or_404(Recipe.objects.filter(
#         category__id=category_id, is_published=True).order_by('-id'))

#     page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

#     return render(request, 'recipes/pages/category.html', context={
#         'recipes': page_obj,
#         'pagination_range': pagination_range,
#         'title': f'{recipes[0].category.name} - Category |'
#     })


# def recipe(request, id):
#     # recipe = Recipe.objects.filter(id=id).first()
#     recipe = get_object_or_404(Recipe, pk=id, is_published=True)
#     return render(request, 'recipes/pages/recipe-view.html', context={
#         'recipe': recipe,
#         'is_detail_page': True,
#     })


# def search(request):
#     search_term = request.GET.get('q', '').strip()

#     if not search_term:
#         raise Http404()

#     recipes = Recipe.objects.filter(
#         Q(
#             Q(title__icontains=search_term) |
#             Q(description__icontains=search_term)
#         ), is_published=True).order_by('-id')

#     page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)

#     return render(request, 'recipes/pages/search.html', {
#         'page_title': f'Search for "{search_term}"',
#         'search_term': search_term,
#         'recipes': page_obj,
#         'pagination_range': pagination_range,
#         'additional_url_query': f'&q={search_term}'
#     })

app/recipes/views/api.py
from django.shortcuts import get_object_or_404
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from app.recipes.permissions import IsOwner
from app.tag.models import Tag

from ..models import Recipe
from ..serializers import RecipeSerializer, TagSerializer


def page_size(size):
    class RecipeAPIv2Pagination(PageNumberPagination):
        page_size = size

    return RecipeAPIv2Pagination


class RecipeAPIv2ViewSet(ModelViewSet):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = page_size(10)
    permission_classes = [IsAuthenticatedOrReadOnly,]
    http_method_names = ['get', 'options', 'head', 'post', 'patch', 'delete']

    def get_serializer_class(self):
        return super().get_serializer_class()

    def get_serializer(self, *args, **kwargs):
        return super().get_serializer(*args, **kwargs)

    def get_queryset(self):
        qs = super().get_queryset()
        category_id = self.request.query_params.get('category_id', '')

        if category_id != '' and category_id.isnumeric():
            qs = qs.filter(category_id=category_id)

        return qs

    def get_object(self):
        pk = self.kwargs.get('pk', '')
        obj = get_object_or_404(
            self.get_queryset(),
            pk=pk
        )
        self.check_object_permissions(self.request, obj)
        return obj

    def get_permissions(self):
        if self.request.method in ['PATCH', 'DELETE']:
            return [IsOwner(), ]
        return super().get_permissions()

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save(author=request.user)
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data,
            status=status.HTTP_201_CREATED,
            headers=headers
        )

    def partial_update(self, request, *args, **kwargs):
        recipe = self.get_object()
        seralizer = RecipeSerializer(
            instance=recipe,
            data=request.data,
            many=False,
            context={'request': request, },
            partial=True
        )
        seralizer.is_valid(raise_exception=True)
        seralizer.save()
        return Response(
            seralizer.data,
        )


'''
class RecipeAPIv2List(ListCreateAPIView):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = page_size(10)
'''

'''
    def get(self, request):
        recipes = Recipe.objects.get_published()[:10]
        serializers = RecipeSerializer(
            instance=recipes,
            many=True,
            context={'request': request},
        )
        return Response(serializers.data)

    def post(self, request):
        serializers = RecipeSerializer(
            context={'request': request}, data=request.data)
        serializers.is_valid(raise_exception=True)
        serializers.save(
            author_id=1, category_id=1, tags=[1, 2])
        return Response(
            serializers.data,
            status=status.HTTP_201_CREATED)
    '''

'''
class RecipeAPIv2Detail(RetrieveUpdateDestroyAPIView):
    queryset = Recipe.objects.get_published()
    serializer_class = RecipeSerializer
    pagination_class = page_size(10)
'''

'''
    def get_recipe(self, pk):
        recipe = get_object_or_404(
            Recipe.objects.get_published(),
            pk=pk
        )
        return recipe

    def get(self, request, pk):
        recipe = self.get_recipe(pk)
        serializers = RecipeSerializer(
            instance=recipe,
            many=False,
            context={'request': request},
        )
        return Response(serializers.data)

    def patch(self, request, pk):
        recipe = self.get_recipe(pk)
        serializers = RecipeSerializer(
            instance=recipe,
            data=request.data,
            many=False,
            context={'request': request},
            partial=True
        )
        serializers.is_valid(raise_exception=True)
        serializers.save()
        return Response(serializers.data)

    def delete(self, request, pk):
        recipe = self.get_recipe(pk)
        recipe.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    '''

'''
@api_view(http_method_names=['get', 'post'])
def recipe_api_list(request):
    if request.method == 'GET':
        recipes = Recipe.objects.get_published()[:10]
        serializers = RecipeSerializer(
            instance=recipes,
            many=True,
            context={'request': request},
        )
        return Response(serializers.data)
    elif request.method == 'POST':
        serializers = RecipeSerializer(
            context={'request': request}, data=request.data)
        serializers.is_valid(raise_exception=True)
        serializers.save(
            author_id=1, category_id=1, tags=[1, 2])
        return Response(
            serializers.data,
            status=status.HTTP_201_CREATED)
'''

'''
@api_view(['get', 'patch', 'delete'])
def recipe_api_detail(request, pk):
    recipe = get_object_or_404(
        Recipe.objects.get_published(),
        pk=pk
    )
    if request.method == 'GET':
        serializers = RecipeSerializer(
            instance=recipe,
            many=False,
            context={'request': request},
        )
        return Response(serializers.data)
    elif request.method == 'PATCH':
        serializers = RecipeSerializer(
            instance=recipe,
            data=request.data,
            many=False,
            context={'request': request},
            partial=True
        )
        serializers.is_valid(raise_exception=True)
        serializers.save()
        return Response(serializers.data)
    elif request.method == 'DELETE':
        recipe.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

    # recipe = Recipe.objects.get_published().filter(pk=pk).first()

    # if recipe:
    #     serializers = RecipeSerializer(instance=recipe, many=False)
    #     return Response(serializers.data)
    # return Response({
    #     'detail': 'Eita',
    # }, status=status.HTTP_404_NOT_FOUND)
'''


@api_view()
def recipe_api_tag(request, pk):
    tag = get_object_or_404(Tag.objects.all(), pk=pk)
    serializers = TagSerializer(instance=tag, many=False)
    return Response(serializers.data)

app/recipes/views/recipe_list.py
import os

from django.db.models import Q
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.utils import translation
from django.utils.translation import gettext as _
from django.views.generic import DetailView, ListView

from app.recipes.models import Recipe
from app.tag.models import Tag
from utils.recipes.pagination import make_pagination

PER_PAGE = int(os.environ.get('PER_PAGE', 6))


class RecipeListViewBase(ListView):
    model = Recipe
    context_object_name = 'recipes'
    paginate_by = None
    ordering = ['-id']
    template_name = 'recipes/pages/home.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            is_published=True
        )
        qs = qs.select_related('author', 'category', 'author__profile')
        qs = qs.prefetch_related('tags')
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_obj, pagination_range = make_pagination(
            self.request,
            ctx.get('recipes'),
            PER_PAGE
        )
        html_language = translation.get_language()
        ctx.update(
            {
                'recipes': page_obj,
                'pagination_range': pagination_range,
                'html_language': html_language,
            }
        )
        return ctx


class RecipeListHome(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'


class RecipeListHomeApi(RecipeListViewBase):
    template_name = 'recipes/pages/home.html'

    def render_to_response(self, context, **response_kwargs):
        recipes = self.get_context_data()['recipes'].object_list.values()
        return JsonResponse(list(recipes), safe=False)


class RecipeListCategory(RecipeListViewBase):
    template_name = 'recipes/pages/category.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(category__id=self.kwargs.get(
            'category_id')
        )

        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        category_traslation = _('Category')
        ctx.update(
            # flake8: noqa
            {'title': f'{ctx.get("recipes")[0].category.name} - {category_traslation} |'}
        )
        return ctx


class RecipeListSearch(RecipeListViewBase):
    template_name = 'recipes/pages/search.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        qs = qs.filter(
            Q(
                Q(title__icontains=search_term) |
                Q(description__icontains=search_term),
            )
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        search_term = self.request.GET.get('q', '')
        ctx.update({
            'page_title': f'Search for "{search_term}"',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}'
        })
        return ctx


class RecipeListTag(RecipeListViewBase):
    template_name = 'recipes/pages/tag.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(
            tags__slug=self.kwargs.get('slug', '')
        )
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        page_title = Tag.objects.filter(
            slug=self.kwargs.get('slug', '')).first()
        if not page_title:
            page_title = 'No recipes found'

        page_title = f'{page_title} - Tag |'
        ctx.update({
            'page_title': f'Search for "{page_title}"',
        })
        return ctx


class RecipeDetail(DetailView):
    model = Recipe
    context_object_name = 'recipe'
    template_name = 'recipes/pages/recipe-view.html'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs.filter(is_published=True)
        return qs

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_page': True,
        })
        return ctx


class RecipeDetailApi(RecipeDetail):
    def render_to_response(self, context, **response_kwargs):
        recipe = self.get_context_data()['recipe']
        recipe_dict = model_to_dict(recipe)

        recipe_dict['criated_at'] = str(recipe.created_at)
        recipe_dict['updated_at'] = str(recipe.updated_at)

        if recipe_dict.get('cover'):
            recipe_dict['cover'] = self.request.build_absolute_uri()[0:22] + \
                recipe_dict['cover'].url[1:]
        else:
            recipe_dict['cover'] = ''

        del recipe_dict['is_published']
        return JsonResponse(recipe_dict, safe=False)

app/recipes/views/theory.py
from django.db.models.aggregates import Count
from django.shortcuts import render

from app.recipes.models import Recipe


def theory(request, *args, **kwagrs):
    recipes = Recipe.object.get_published()
    number_of_recipes = recipes.aggregate(number=Count('id'))
    context = {
        'recipes': recipes,
        'number_of_recipes': number_of_recipes['number'],
    }
    return render(
        request,
        'recipes/pages/theory.html',
        context=context,
    )

app/recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
    integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
<link rel="stylesheet" href="{% static 'global/css/global-styles.css'%}">

app/recipes/templates/recipes/partials/recipe.html
{% load i18n %}

<div class="recipe recipe-list-item">
    {% if recipe.cover %}
        <div class="recipe-cover">
            <a href="{{recipe.get_absolute_url}}">
                <img src="{{recipe.cover.url}}" alt="Temporario">
            </a>
        </div>
    {%endif%}
    <div class="recipe-title-container">
        <h2 class="recipe-title">
            <a href="{{recipe.get_absolute_url}}">
                {{recipe.title}}
            </a>
        </h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
            {% if recipe.author is not None %}
                {% if recipe.author.profile %}
                    <a href="{%url 'authors:profile' recipe.author.profile.id%}">
                {% endif %}
                {% if recipe.author.first_name %}
                    {{recipe.author.first_name}} {{recipe.author.last_name}}
                {% else %}
                    {{recipe.author.username}}
                {% endif %}
                {% if recipe.author.profile %}
                    </a>
                {% endif %}
            {% else %}
                Desconhecido
            {% endif %}
        </span>
        
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }} às {{ recipe.created_at|date:"H:i:s" }}
        </span>
        {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
        {%endif%}
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>{% translate "Preparation" %}</h3>
            <div class="recipe-meta-text">
                {{recipe.preparation_time}} {{recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> {% translate "Servings" %}</h3>
            <div class="recipe-meta-text">
                {{recipe.servings}} {{recipe.servings_unit }}
            </div>
        </div>
    </div>

    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>{% translate 'read more' %}...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {% if recipe.preparation_steps_is_html is True %}
                {{recipe.preparation_steps|safe}}
            {% else %}
                {{recipe.preparation_steps|linebreaksbr}}
            {% endif %}

            {% if recipe.tags.all %}
                <p>
                    Tags:
                    {% for tag in recipe.tags.all  %}
                    <a href="{%url 'recipes:tag' tag.slug %}">
                        {{tag.name}}
                    </a>, 
                    {% endfor %}
                </p>
            {% endif %}
        </div>
    {% endif %}
</div>